name: static-build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ndk-setup
        uses: nndixon/setup-ndk@v1
        with:
          ndk-version: r25c
      - name: compile
        run: |
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang++ \
          -shared src/main.cpp -o libstatic.so -llog -landroid
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: libstatic.so

